### ISSUE TITLE
Can't give permission with LuckPerms

### ISSUE THREAD

**Issue by Egorrko** [Londiuh/login#1]
When i tried install your mod and that: https://luckperms.net/
I can't login in game. Server return me "No Permission".
Have Your mod  permission settings?
How i can configure that?

**Comment by Egorrko** [comment]
I was wrong and problem was not in luckperms. It was in [cardboard](https://github.com/CardboardPowered/cardboard) mod.
Anyway i get "No Permission" and idk how to fix it.

**Comment by Londiuh** [comment]
I'm not sure how Bukkit's `permissions.yml` works. 

I tried this but doesn't work:
```yml
default:
  description: default
  default: true
  permissions:
    minecraft.command.login: true
```
Maybe you can use some perms plugin to configure /login and /register perms. You can also use a bukkit/spigot login plugin.
